version: '3.4'

services:
  photos:
    image: K3nPhotos
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MONGO_HOST=mongodb://mongodb/
      - MONGO_PORT=27017
    depends_on:
      - mongodb
    ports:
      - "0.0.0.0:1405:1405"
    links:
      - mongodb:mongo
    volumes:
      - /app/photos

  mongodb:
    image: mongo:4.4.7-focal
    volumes:
      - mongo:/data/db


volumes:
  mongo:


