version: '3.4'

services:
  users:
    image: K3nUsers
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MONGO_HOST=mongodb://mongodb/
      - MONGO_PORT=27017
    depends_on:
      - mongodb
    ports:
      - "0.0.0.0:1406:1406"
    links:
      - mongodb:mongo
    volumes:
      - /app/avatars

  mongodb:
    image: mongo:4.4.7-focal
    volumes:
      - mongo:/data/db


volumes:
  mongo:


