version: '3.4'

services:
  spaces:
    image: K3nSpaces
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MONGO_HOST=mongodb://mongodb/
      - MONGO_PORT=27017
    depends_on:
      - mongodb
    ports:
      - "0.0.0.0:1412:1412"
    links:
      - mongodb:mongo

  mongodb:
    image: mongo:4.4.7-focal
    volumes:
      - mongo:/data/db


volumes:
  mongo:


